apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  labels:
    app: whereami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
        - name: frontend
          image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.20
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whereami
  name: whereami
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: whereami